### ISSUE TITLE
Alert message about missing Less module in the backend

### ISSUE THREAD

**Issue by webmanufaktur** [baumrock/RockFrontend#1]
After installing the module into a clean/new ProcessWire instance while using the blank profile (blank profile for RockFrontend) an alert message pops up telling me to install the Less module.

This alert would be fine in the frontend but in the backend (on each page load) is a bit off.

![2022-08-10_21-40](https://user-images.githubusercontent.com/5909089/184006066-799cb6af-bf3e-4e48-abc3-53155a71f50e.png)

**Comment by BernhardBaumrock** [comment]
Hey @webmanufaktur (thx for adding the vocals!)
I've pushed a fix for this, thx :)
