### ISSUE TITLE
possible to specify more than one template in the renderIf method?

### ISSUE THREAD

**Issue by protrolium** [baumrock/RockFrontend#11]
Hi, 

Looking to see if I can specify more than a single template in renderIf method: 
`<?= $rockfrontend->renderIf("sections/includes/related-items.latte", "template=template1") ?>`

would you simply rewrite the template declaration?

`<?= $rockfrontend->renderIf("sections/includes/related-items.latte", "template=template1, template=template2") ?>`

Thanks,

**Comment by BernhardBaumrock** [comment]
Hi @protrolium 

It's just a regular PW page selector, so the syntax is `template=tempate1|template2`
