### ISSUE TITLE
Alfred ignores field overrides when called from repeater matrix template

### ISSUE THREAD

**Issue by stizzlestizzle** [baumrock/RockFrontend#13]
Hi Bernhard,

- I have an image field named `image_content_half`. Let's say I have filled its note field with value "Foo".
- I have a Repeater Matrix type `text_image` which is using this image field. From the fields list for `text_image` I have overriden the notes of the `image_content_half` field to "Bar".
- I am rendering my matrix field as suggested: `{$rockfrontend->render($page->matrix)}`
- Inside the template for my Repeater Matrix type `(/site/templates/fields/matrix/text_image.latte)` I am calling Alfred for the particular field:
```
...
<div class="bla" {alfred($page, ['fields'=> 'image_content_half'])|noescape}>
  <img ...>
</div>
...

```

- I would expect the field notes of `image_content_half` to show the override value "Bar" but instead it shows the original value "Foo"
- (this is not only the case with notes, but basically with any override including e.g. required property)
- (when editing via ProcessWire admin the field overrides work correctly)

RockFrontend 2.9.1, RepeaterMatrix 0.0.8, ProcessWire 3.0.200

Am I missing something or is this a bug?

Thank you in advance.

**Comment by BernhardBaumrock** [comment]
Hey @stizzlestizzle I'm not sure if that is related to RockFrontend. RockFrontend/Alfred is only showing the page editor in a modal window. You can also click on the edit icon and open that page in a new tab. You can then also remove the ?modal=1 (or similar) to get the regular page editor with header + footer of the PW backend.

I think the most likely issue is that maybe it's a bug with RepeaterMatrix that when it is opened via custom url (?field=my_repeatermatrix_field) it does not apply field overrides?

Is that what describes your issue?

**Comment by stizzlestizzle** [comment]
Thanks for getting back so quickly.

You are correct: Opening directly `https://.../processwire/page/edit/?id=1304&fields=image_content_half` does indeed also ignore the field overrides.

Closing this issue.
