### ISSUE TITLE
did new version alter behavior or LESS files being parsed?

### ISSUE THREAD

**Issue by protrolium** [baumrock/RockFrontend#16]
I have Rockfrontend 2.1.4 in a Processwire install and it seems to catch all the individual `.less` files in the `/templates/sections` folder automatically with this declaration in `_main.php`

```
$rockfrontend
	->styles()->setOptions(['autoload'=>true])
	->add("/site/templates/uikit-3.15.10/src/less/uikit.theme.less")
	->add("/site/templates/styles/custom.less")
	;
```

I have another Processwire site with Rockfrontend 2.12 and it doesn't catch any `.less` files unless I add with the `addAll` method.

```
$rockfrontend
	->styles()->setOptions(['autoload'=>true])
	->add("/site/templates/uikit-3.15.20/src/less/uikit.theme.less")
	->addAll("/site/templates/sections")
	->add("/site/templates/styles/custom.less")
	;
```

How come it works in the first example but only with `addAll` in newer version ? 
Thanks

**Comment by BernhardBaumrock** [comment]
Hey @protrolium sorry for the trouble :) 

Yes, I have changed the way RockFrontend includes default styles from `->setOptions(['autoload'=>true])` to the more meaningful and easier to understand `->addDefaultFolders()`.

See here for the setup that I'm using on all my projects: https://github.com/baumrock/RockFrontend/blob/c4669e394b5afe5641ca0b2102157f874453510e/profiles/rock/files/site/templates/_main.php#L16

Does that help? Then please close the issue, thx :)

**Comment by protrolium** [comment]
good to know! I will adjust accordingly in my installs. thanks.
