### ISSUE TITLE
Webfonts

### ISSUE THREAD

**Issue by eydun** [baumrock/RockFrontend#17]
I can not get webfonts to work.

I am supposed to write the full url?

When I try to write https://fonts.google.com/specimen/Roboto, I get this error:
![image](https://github.com/baumrock/RockFrontend/assets/12867/4ef9d71b-9f98-4b56-91a3-9103b0ed6711)

![image](https://github.com/baumrock/RockFrontend/assets/12867/20dce8e1-296a-4fee-b789-10c030e8f04d)

**Comment by BernhardBaumrock** [comment]
Thx @eydun I've added instructions how to use this feature in the latest commit on the dev branch: https://github.com/baumrock/RockFrontend/commit/77ca1861ad6cb45c7555be1ca5e14a39f386a116
