### ISSUE TITLE
Page not available in AutoPrepend.php

### ISSUE THREAD

**Issue by millipedia** [baumrock/RockFrontend#21]
I think this is the same thing that GornyCreative mentioned in 

https://processwire.com/talk/topic/27417-rockfrontend-%F0%9F%9A%80%F0%9F%9A%80-the-powerful-toolbox-for-processwire-frontend-development/?do=findComment&comment=238061

but I thought it worth logging here as well. 

When I installed RockFrontend just now on an up to date version of PW (although a duplicated site rather than a fresh install) it dies with  a fatal error 'Call to member function getFiles() on null' (screenshot attached).

Just wrapping the foreach loop in a conditional that checks for page lets me continue with no obvious problems ... so far :-)

`if(isset($page) && $page){
  foreach ($page->getFields() as $field) {
    if (!array_key_exists($field->name, $vars)) continue;
    unset($vars[$field->name]);
  }
} `

![autoprepend_error](https://github.com/baumrock/RockFrontend/assets/1379269/f683b92f-e6c5-47ba-8d08-13a2d767c0ff)

Thanks for all your work on this and all things PW of course.

**Comment by BernhardBaumrock** [comment]
Thx @millipedia could you please check if the latest version on the dev branch fixes this?

**Comment by millipedia** [comment]
Nearly ... it doesn't throw an error any more but Tracy is still showing showing a warning:

PHP Warning: Undefined variable $page in .../public_html/site/modules/RockFrontend/AutoPrepend.php:17

**Comment by BernhardBaumrock** [comment]
@millipedia thx that would also be an easy fix, but do you have steps for me to reproduce this? I'm asking because I'm seeing sometimes that variables in _init.php are not available at later use. Also @jmartsch had issues with defining variables in _init.php so that might all be the same issue.

**Comment by millipedia** [comment]
Well it took a couple of cups of coffee and a bit of hunting down, but I can repeat it consistently now. The issue is a clash with macura's ( @outflux3 ) SettingsFactory module.

On a clean install of PW install SettingsFactory and set up a field for it using a php file with a simple inputfield definition (I'm just using a field from the examples included . 

Then when we install RockFrontend we get the error about $page being null.

Quite what SettingsFactory is doing I'm not sure but hopefully that's some help. Not sure that sounds like the same thing as the _init.php variables problem but maybe it will shed some light on it.

Let me know if I can help with anything and thanks again for everthing.

**Comment by outflux3** [comment]
Hi - let me know if there's anything i can do in Settings Factory to help with this. That module is fairly simple, not a lot going on, and it's supposed to be confined to the admin, but if there is something that can be amended to cooperate with RockFrontend it should be simple to fix.

**Comment by BernhardBaumrock** [comment]
Hey @millipedia  and @outflux3 thx for your help and offer to help.

I did the following:
- fresh install of pw latest dev
- installed settings factory and used kitchen-sink.json
- installed RockFrontend latest MAIN (because dev has the isset() already) --> no errors
- installed tracydebugger --> no errors
- uninstalled RockFrontend --> no errors
- installed RockFrontend --> no errors
- enabled livereload --> no errors
- views frontend and backend pages --> no errors

I'd need more precise instructions please so that I can track it down.

**Comment by millipedia** [comment]
Curiouser and curioser .....  using kitchen-sink.json doesn't throw the error but using kitchen-sink.php does

![kitchen_sinks](https://github.com/baumrock/RockFrontend/assets/1379269/e315afcf-d376-4240-b0ee-d778023c5e77)

**Comment by BernhardBaumrock** [comment]
Great, now everything makes sense! Thx for tracking it down. The solution I just pushed might fix other issues as well, so this  is for sure better then just quick-fixing it and was worth the effort :)
