### ISSUE TITLE
Exclude .afdesign file from ZIP?

### ISSUE THREAD

**Issue by netcarver** [baumrock/RockFrontend#24]
@BernhardBaumrock Hi Bernhard!

Curious about the https://github.com/baumrock/RockFrontend/blob/main/RockFrontend.afdesign file - presumably this is an affinity designer save that's been included in the download zip.

Could this be excluded from the installed files as things like this really don't need to end up in live sites when the module is installed?

**Comment by BernhardBaumrock** [comment]
Yes, it's a 30kB source file that I can use to create logos for my modules. It's just easier for me to have it in the dedicated modules and not somewhere else, but I could also move those files into my cloud. I'll go ahead and do so even though I don't think it does any harm?
