### ISSUE TITLE
Intermittent live reload issues

### ISSUE THREAD

**Issue by netcarver** [baumrock/RockFrontend#27]
@BernhardBaumrock Hi Bernhard. Not sure if this is actually an issue or not, but I'm seeing intermittent issues with livereloads on the front end. Seems to be correlated with these notices in the console...

![image](https://github.com/baumrock/RockFrontend/assets/16049/74e3c6d1-ebd0-48f4-bab3-8d568cba595d)

I will keep an eye out for more occurances and investigate further - but I'm starting to wonder if this is related to not being logged in to the admin interface at the same time as seeing these in the front end.

**Comment by BernhardBaumrock** [comment]
Hi @netcarver I'm also seeing this from time to time, just didn't find motivation to fix it. I think it's coming up when the window is open for too long and the stream breaks for whatever reason. We could do some polling to reestablish the connection I guess, but as it's a simple page reload to fix it I didn't look into it...
If you find time I'll happily merge it :)

**Comment by BernhardBaumrock** [comment]
@netcarver any news so far? I'll close the issue. Please reopen it if need be!
