### ISSUE TITLE
sitemap error on multi-language

### ISSUE THREAD

**Issue by gs-chofmann** [baumrock/RockFrontend#28]
On Multilanguage Websites the sitemap.xml is broken

![image](https://github.com/baumrock/RockFrontend/assets/109527558/9b1acaac-665f-4095-8301-fa01ad021c57)

Fix:

 urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml"

instead of

urlset xmlns='http://www.sitemaps.org/schemas/sitemap/0.9'

**Comment by BernhardBaumrock** [comment]
Hey @gs-chofmann thx, could you please provide more details and let me know how I can reproduce this?

**Comment by gs-chofmann** [comment]
You should be able to reproduce it on every installation with more than one language.

Just install the plugin on a multi language installation and open up the sitemap.xml on Google Chrome. Then the error occurs as mentioned in the screenshot above.

It is because you implement the xhtml:link for the href lang tags - but the xhtml:link has no specification.

For more see https://stackoverflow.com/questions/39450542/namespace-prefix-xhtml-on-link-is-not-defined-sitemap-xml

**Comment by BernhardBaumrock** [comment]
Thx, I've added your suggested fix!
