### ISSUE TITLE
CSS and Less files get autoloaded

### ISSUE THREAD

**Issue by webmanufaktur** [baumrock/RockFrontend#3]
Existing **CSS** and **Less** files within _/site/templates/sections/_ get autoloaded even though `$rockfrontend->styles()->...` isn't used anywhere. 

![2022-08-11_00-09](https://user-images.githubusercontent.com/5909089/184029807-09fd30a3-88ad-49dd-9cb3-c27b818e6865.png)

While this autoload feature is nice in general, right now and in this way it ends up in really unexpected results.

**Comment by BernhardBaumrock** [comment]
Hey @webmanufaktur thx for letting me know - maybe I was too eager on that one, sorry! I'm using LESS so I didn't realize that it makes troubles, I'll fix this asap :)

**Comment by BernhardBaumrock** [comment]
There's no the option to disable autoloading:
```php
$rockfrontend->styles()->setOptions(['autoload'=>false]);
```

**Comment by webmanufaktur** [comment]
Setting this option works as expected.
