### ISSUE TITLE
Missing parameter for seo()->setValue in the Docs

### ISSUE THREAD

**Issue by inreti-sb** [baumrock/RockFrontend#32]
After struggling with setting the value for a new meta-tag, I realized the Docs are missing a parameter under
https://www.baumrock.com/en/processwire/modules/rockfrontend/docs/seo/#setvalue

Should be
```
$rockfrontend->seo()
  ->setValue("foo", $page->title);
```
instead of
```
$rockfrontend->seo()
  ->setValue($page->title);
```

In my opinion an additional example with both functions together could be helpful:

```
$rockfrontend->seo()
  ->setMarkup("foo", "<meta property='foo' content='{value:20}'>")
  ->setValue("foo", $page->title);
```
Thanks for RockFrontend, @BernhardBaumrock !

**Comment by BernhardBaumrock** [comment]
Thank you very much @inreti-sb  :) I've pushed it to the dev branch and it will be merged soon
