### ISSUE TITLE
Alfred CSS/JS even without Alfred enabled

### ISSUE THREAD

**Issue by webmanufaktur** [baumrock/RockFrontend#4]
The Alfred CSS and JS files were added to the source even though alfred($page) isn't used anymore anywhere.

This only happens when logged in (only superuser tested). Guest won't see anything from Alfred.

Could be a decision that was made but looks like an unwanted feature for now.

![2022-08-11_00-19](https://user-images.githubusercontent.com/5909089/184030514-6e3e4b6e-6625-4cc8-bc69-ec88cbebf6c9.png)

**Comment by BernhardBaumrock** [comment]
Thx for pushing @webmanufaktur that's the intended behaviour. It was just easier like that, but it's also easy to fix it, so I'll add this soon!

**Comment by BernhardBaumrock** [comment]
Can you please try version 1.14.1 ? @webmanufaktur and let me know if everything works as expected?

**Comment by webmanufaktur** [comment]
Perfect!
